name: EMAMI Validation Pipeline 
on:
  workflow_dispatch:
    inputs:
      Feature_Branch:
        type: String
        description: Please Enter Branch To validate in Environment. 
        required: true
      environment:
        type: choice
        description: Please Select The Validation Environment.
        options:
          - EMAMI QA
          - EMAMI QAGlobal
          - EMAMI UAT
          - EMAMI HOTFIX
        default: "EMAMI QA"
        required: true
      testlevel:
        type: choice
        description: Select Test class Run Type.
        options:
          - NoTestRun
          - RunLocalTests
          - RunSpecifiedTests
          - RunAllTestsInOrg
        default: "RunSpecifiedTests"
        required: true
      specifiedclass:
        type: String
        description: Please Enter Test Class Names with Comma Seperated.

jobs:
  Validation_To_EMAMI_QA:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'EMAMI QA' }}
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli@latest
          sfdx --version
      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner@latest

      - name: Generate JWT Key for ${{ github.event.inputs.environment }}
        shell: bash
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
  
      - name: Authorize To ${{ github.event.inputs.environment }}
        run: |
          sf org login jwt --client-id ${{secrets.SALESFORCE_CONSUMER_KEY_EMAMI_QA }} \
                 --jwt-key-file server.key \
                 --username ${{ secrets.SFDX_AUTH_EMAMI_QA_USERNAME }} \
                 --instance-url https://test.salesforce.com \
                 --set-default-org				 				                        
      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --normalize-severity --target . --outfile results.html --verbose
          results-artifact-name: salesforce-code-analyzer-results
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.exit-code }}"
      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
      - name: validation with RunLocalTests for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunLocalTests'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen}  --targetusername  ${{ secrets.SFDX_AUTH_EMAMI_QA_USERNAME }} --testlevel ${{github.event.inputs.testlevel}}

      - name: validation with RunAllTestsInOrg for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunAllTestsInOrg'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_EMAMI_QA_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} 

      - name: validation with NoTestRun for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'NoTestRun'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_EMAMI_QA_USERNAME }} 

      - name: validation with RunSpecifiedTests for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunSpecifiedTests'}}  
        run: sf project deploy validate  -x ${SFDX_Package_Gen} --target-org ${{ secrets.SFDX_AUTH_EMAMI_QA_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} -tests ${SFDX_testclass} -w 500

  Validation_To_EMAMI_QAGlobal:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'EMAMI QAGlobal' }}
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli@latest
          sfdx --version
      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner@latest

      - name: Generate JWT Key for ${{ github.event.inputs.environment }}
        shell: bash
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key

      - name: Authorize To ${{ github.event.inputs.environment }}
        run: |
          sfdx force:auth:jwt:grant --client-id=${{secrets.SALESFORCE_CONSUMER_KEY_EMAMI_QAGLOBAL }} --jwt-key-file=server.key --username=${{ secrets.SFDX_AUTH_EMAMI_QAGLOBAL_USERNAME }} --set-default-dev-hub
      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --normalize-severity --target . --outfile results.html --verbose
          results-artifact-name: salesforce-code-analyzer-results
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.exit-code }}"
      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
      - name: validation with RunLocalTests for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunLocalTests'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen}  --targetusername  ${{ secrets.SFDX_AUTH_EMAMI_QAGLOBAL_USERNAME }} --testlevel ${{github.event.inputs.testlevel}}

      - name: validation with RunAllTestsInOrg for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunAllTestsInOrg'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_EMAMI_QAGLOBAL_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} 

      - name: validation with NoTestRun for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'NoTestRun'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_EMAMI_QAGLOBAL_USERNAME }} 

      - name: validation with RunSpecifiedTests for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunSpecifiedTests'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_EMAMI_QAGLOBAL_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} --runtests ${SFDX_testclass}
  Validation_To_EMAMI_UAT:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'EMAMI UAT' }}
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli@latest
          sfdx --version
      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner@latest

      - name: Generate JWT Key for ${{ github.event.inputs.environment }}
        shell: bash
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
  
      - name: Authorize To ${{ github.event.inputs.environment }}
        run: |
          sfdx force:auth:jwt:grant --client-id=${{secrets.SALESFORCE_CONSUMER_KEY_EMAMI_UAT }} --jwt-key-file=server.key --username=${{ secrets.SFDX_AUTH_EMAMI_UAT_USERNAME }} --set-default-dev-hub
      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --normalize-severity --target . --outfile results.html --verbose
          results-artifact-name: salesforce-code-analyzer-results
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.exit-code }}"
      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
      
      - name: validation with RunLocalTests for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunLocalTests'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen}  --targetusername  ${{ secrets.SFDX_AUTH_EMAMI_UAT_USERNAME }} --testlevel ${{github.event.inputs.testlevel}}

      - name: validation with RunAllTestsInOrg for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunAllTestsInOrg'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_EMAMI_UAT_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} 


      - name: validation with NoTestRun for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'NoTestRun'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_EMAMI_UAT_USERNAME }} 

      - name: validation with RunSpecifiedTests for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunSpecifiedTests'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_EMAMI_UAT_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} --runtests ${SFDX_testclass}
  Validation_To_EMAMI_Hotfix:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'EMAMI HOTFIX' }}
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli@latest
          sfdx --version
      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner@latest
        
      - name: Generate JWT Key for ${{ github.event.inputs.environment }}
        shell: bash
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
  
      - name: Authorize To ${{ github.event.inputs.environment }}
        run: |
          sfdx force:auth:jwt:grant --client-id=${{secrets.SALESFORCE_CONSUMER_KEY_EMAMI_HOTFIX }} --jwt-key-file=server.key --username=${{ secrets.SFDX_AUTH_EMAMI_HOTFIX_USERNAME }} --set-default-dev-hub
      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --normalize-severity --target . --outfile results.html --verbose 
          results-artifact-name: salesforce-code-analyzer-results
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.exit-code }}"
      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
      - name: validation with RunLocalTests for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunLocalTests'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen}  --targetusername  ${{ secrets.SFDX_AUTH_EMAMI_HOTFIX_USERNAME }} --testlevel ${{github.event.inputs.testlevel}}

      - name: validation with RunAllTestsInOrg for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunAllTestsInOrg'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_EMAMI_HOTFIX_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} 

      - name: validation with NoTestRun for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'NoTestRun'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_EMAMI_HOTFIX_USERNAME }} 

      - name: validation with RunSpecifiedTests for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunSpecifiedTests'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_EMAMI_HOTFIX_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} --runtests ${SFDX_testclass}